apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wmla-uploader.name" . }}-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
