apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: default
spec:
  ports:
  - port: {{ .Values.redis.port }}
    protocol: {{ .Values.redis.protocol }}
    targetPort: {{ .Values.redis.port }}
  selector:
    name: {{ .Values.redis.name }}
  sessionAffinity: None
  type: {{ .Values.redis.service.type }}
