apiVersion: v1
kind: Pod
metadata:
  labels:
    name: {{ .Values.redis.name }}
  name: {{ .Values.redis.name }}
  namespace: default
spec:
  containers:
  - args:
    - --requirepass
    - $(REDIS_PASSWORD)
    command:
    - redis-server
    env:
    - name: REDIS_PASSWORD
      value: {{ .Values.redis.env.password }}
    image: redis:5.0.4
    imagePullPolicy: IfNotPresent
    name: {{ .Values.redis.name }}
    ports:
    - containerPort: {{ .Values.redis.port }}
      protocol: {{ .Values.redis.protocol }}
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File