kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "wmla-uploader.name" . }}-route
  namespace: default
spec:
  to:
    kind: Service
    name: {{ include "wmla-uploader.name" . }}
    weight: 100
  port:
    targetPort: {{ .Values.uploader.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
