apiVersion: v1
kind: Service
metadata:
  name: {{ include "wmla-uploader.name" . }}
  namespace: default
spec:
  ports:
  - port: {{ .Values.uploader.port }}
    protocol: {{ .Values.uploader.protocol }}
    targetPort: {{ .Values.uploader.port }}
  selector:
    name: {{ include "wmla-uploader.name" . }}
  sessionAffinity: None
  type: {{ .Values.uploader.service.type }}
