apiVersion: v1
kind: Pod
metadata:
  labels:
    name: {{ include "wmla-uploader.name" . }}
  name: {{ include "wmla-uploader.name" . }}
  namespace: default
spec:
  containers:
  - image: quay.io/marwan_attar_ibm/wmla-file-uploader
    imagePullPolicy: Always
    name: {{ include "wmla-uploader.name" . }}
    ports:
    - containerPort: {{ .Values.uploader.port }}
      protocol: {{ .Values.uploader.protocol }}
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    securityContext:
      runAsUser: {{ .Values.uploader.securityContext.runAsUser.groupId }}
      runAsGroup: {{ .Values.uploader.securityContext.runAsGroup.groupId }}
    volumeMounts:
    - mountPath: /var/run/data
      name: data
  serviceAccountName: {{ include "wmla-uploader.name" . }}-sa
  securityContext:
    fsGroup: {{ .Values.uploader.securityContext.fsGroup.groupId }}
    supplementalGroups: [5777, 5888]
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: {{ include "wmla-uploader.name" . }}-pvc
  restartPolicy: Always
  schedulerName: default-scheduler
