---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: uploader-role
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["uploader-scc"]
    verbs: ["use"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-scc-tutorial-scc
subjects:
  - kind: ServiceAccount
    name: uploader-sa
roleRef:
  kind: Role
  name: uploader-role
  apiGroup: rbac.authorization.k8s.io
